// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Generated from the docs/ folder structure, ordered by each page's
  // sidebar_position.
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
